<?php
/**
 * @author: @davidselo
 * @description:  Aquí vamos a  poner una serie de botones que al ser pulsados tienes que realizar una petición Ajax
 * */
?>
<div id="botones-ajax">
	<button onclick="setLocation('http://local.pruebas.com/coalesce-functioning-on-impatience-t-shirt.html?options=cart')" class="button btn-ajax-header" title="Carga el Header" type="button"><span><span>Cargar Header</span></span></button>
	<button onclick="setLocation('http://local.pruebas.com/coalesce-functioning-on-impatience-t-shirt.html?options=cart')" class="button btn-ajax-left" title="Carga el Left" type="button"><span><span>Cargar Left</span></span></button>
	<button onclick="setLocation('http://local.pruebas.com/coalesce-functioning-on-impatience-t-shirt.html?options=cart')" class="button btn-ajax-rigth" title="Carga el Rigth" type="button"><span><span>Cargar Rigth</span></span></button>
	<button onclick="setLocation('http://local.pruebas.com/coalesce-functioning-on-impatience-t-shirt.html?options=cart')" class="button btn-ajax-content" title="Carga el Rigth" type="button"><span><span>Cargar Content</span></span></button>
	<button onclick="setLocation('http://local.pruebas.com/coalesce-functioning-on-impatience-t-shirt.html?options=cart')" class="button btn-ajax-footer" title="Carga el Footer" type="button"><span><span>Cargar Footer</span></span></button>
</div>