<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Sample
 * @package     Sample_WidgetTwo
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var $this Sample_WidgetTwo_Block_List
 * @see Sample_WidgetTwo_Block_List
 */
?>
<?php foreach ($list as $item) : ?>
    <a <?php echo $item['attributes']; ?>><img src="<?php echo $item['image']; ?>" title="<?php echo $item['text']; ?>" border="0" /></a>
<?php endforeach; ?>
