<h2>Rick</h2>
<object width ="640" height ="505 ">
<param name ="movie" value ="http://www.youtube.com/v/'<?php
echo $this -> getVideoId ();?>?fs=1&amp;hl=en_US"></param>
<param name ="allowFullScreen" value ="true"></param>
<param name ="allowscriptaccess" value ="always"></param>
<embed src ="http://www.youtube.com/v/<?php
echo $this->getVideoId();?>?fs=1&amp;hl=en_US"
type ="application/x-shockwave-flash"allowscriptaccess ="always"
allowfullscreen ="true" width ="640" height ="505"></embed>
</object>